name: Deploy akello.io
on:
  workflow_run:
    workflows: [ "Run API Server Tests" ]
    branches: [ main ]
    types:
      - completed      
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages, test and build artifacts
        working-directory: packages/docs
        run: |
          npm i -D
          npm test --if-present
          npm run build:prod
        env:
          CI: true
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: build
          path: build
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Download artifacts        
        uses: actions/download-artifact@master
        with:
          name: build
          path: build
      - name: Remove existing artifacts from AWS S3
        working-directory: packages/docs
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 rm \
          s3://akello.io \
          --recursive \
          --region us-east-1
      - name: Deploy artifacts to AWS S3
        working-directory: packages/docs
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
          ./build s3://akello.io \
          --recursive \
          --acl public-read \
          --region us-east-1