name: Deplooy Fast API Server
run-name: ${{ github.actor }} is deploying to demo 🚀
on: [push]
jobs:
  Deploy-FastAPI-Demo:
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker
        working-directory: ./packages/server
        run: docker build -t demo-akello-io .
      - name: Push to ECR
        id: ecr
        uses: jwalton/gh-ecr-push@v1.3.6
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1
          local-image: demo-akello-io
          image: demo-akello-io:latest
